project:
  type: website
  # output-dir: docs

website:
  page-navigation: true
  title: "Agastya Patel"
  navbar:
    left:
      - notes/index.qmd
      - index.qmd
      - projects.qmd
      - text: "X/twitter: @4gastyaPatel"
        aria-label: "X (Twitter)"
        href: https://twitter.com/4gastyaPatel
        target: _blank
    right:
      - text: About Me
        href: about.qmd
      - icon: github
        href: https://github.com/AgastyaPatel
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/4gastyapatel/
        target: _blank

  page-footer: 
    border: true
    left: "Copyright 2024, Agastya Patel" 
    right: 
      - icon: github
        href: https://github.com/AgastyaPatel
      - icon: twitter 
        href: https://twitter.com/4gastyaPatel

  sidebar:
      title: 'Notes'
      pinned: false
      collapse-level: 2
      style: docked
      search: true
      contents: 
        - section: "Notes"
          contents: notes/**
        - section: "Blogs"
          contents: blogs/**
format:
  html:
    css: styles.css
    toc: true
    theme:
      light: cosmo
      # dark: [cosmo, theme-dark.scss]
    mainfont: "Roboto Mono"
      
execute:  
  freeze: auto