project:
  type: website
  # output-dir: docs

website:
  page-navigation: true
  title: "Agastya Patel"
  navbar:
    left:
      - notesIndex.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AgastyaPatel
      - icon: twitter
        href: https://twitter.com/4gastyaPatel
      - icon: linkedin
        href: https://twitter.com/in/4gastyaPatel

  page-footer: 
    border: true
    left: "Copyright 2024, Agastya Patel" 
    right: 
      - icon: github
        href: https://github.com/AgastyaPatel
      - icon: twitter 
        href: https://twitter.com/4gastyaPatel

  # sidebar: 
  #   style: "docked"
  #   search: true
  #   contents:
  #     - section: "Basics"
  #       contents:

format:
  html:
    css: styles.css
    toc: true
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
      
execute:
  freeze: auto